# Built with Jekyll 3.2.0

# Setup
title:               Trust, Politics and Fear 
tagline:             'Growing up in the Age of Terror'
description:         'Stories..'
url:                 'https://trustpoliticsfear.github.io'
baseurl:             '/'

# About/contact
author:
  name:             Randa Abdel-Fattah
  url:              "https://researchers.mq.edu.au/en/persons/randa-abdel-fattah/projects/?status=RUNNING"
  email:            randa.abdel-fattah@mq.edu.au

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
